### ISSUE TITLE
client_secret.json is not valid, root property 'installed' missing

### ISSUE THREAD

**Issue by SamuraiJack365** [ismarslomic/google-assistant-oauth#2]
When I try to run the command (with or without sudo):

```
docker run --rm \
-p 3005:3005 \
-v /home/[user]/google:/usr/src/config \
ismarslomic/google-assistant-oauth:latest
```

```
TypeError: Cannot read properties of undefined (reading 'token_uri')
    at validateClientSecretFile (/usr/src/app/index.js:132:25)
    at main (/usr/src/app/index.js:16:3)
    at Object.<anonymous> (/usr/src/app/index.js:143:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```
The contents of "client_secret.json" (with sensitive data replaced with placeholders) is:

```
{"web":{"client_id":"[client_id]","project_id":"[project_id]","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"[client_secret]","redirect_uris":["[redirect_uris]"]}}
```

**Comment by ismarslomic** [comment]
This is because the content of your client_secret is not correct. I have updated [README](https://github.com/ismarslomic/google-assistant-oauth#example-of-correct-client_secret-file) with what content is expected and also updated the validation logic in container to provide more user friendly error message. 

To solve your issue, please make sure you follow precisely the steps described in the official Google documentation: https://developers.google.com/assistant/sdk/guides/service/python/embed/config-dev-project-and-account

**Comment by SamuraiJack365** [comment]
The key difference is when I setup the credentials I had selected "web application" rather than your expected "desktop app" which made the root property be "web" rather than "installed" as your code is expecting, the rest of the JSON is valid. I had forked your repo for this and the broadcast to modify it to look for the web property instead and it worked fine for me now. I would update your README to mention you need to select "desktop app" when setting up the credentials.

**Comment by ismarslomic** [comment]
Thanks! I have updated docs!
